import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider
            appearance={{
                layout: {
                    socialButtonsPlacement: 'bottom',
                    socialButtonsVariant: 'blockButton',
                    termsPageUrl: 'https://clerk.com/terms',
                    privacyPageUrl: 'https://clerk.com/privacy',
                    helpPageUrl: 'https://clerk.com/help',
                },
                variables: {
                    colorPrimary: 'black',
                    colorText: 'black',
                },
            }}
        >
            <html lang="en">
                <body className={inter.className}>{children}</body>
            </html>
        </ClerkProvider>
    );
}
